version: "3.9"

services:

  kub-postgres:
    image: "docker.io/bitnami/postgresql-repmgr:15"
    container_name: "postgresql-repmgr"
    restart: unless-stopped
    ports:
      - "5433:5433"
    volumes:
        - "./postgres:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=customuser
      - REPMGR_PRIMARY_HOST=n1.oze.li
      - REPMGR_PRIMARY_PORT=5433
      - REPMGR_PARTNER_NODES=n1.oze.li:5433,granite.ozeliurs.com:5433
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=n1.oze.li
      - REPMGR_PORT_NUMBER=5433
    env_file:
      - .postgres.env


networks:
  traefik:
    external: true